// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dzwodetapyeiqucnnhmd.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6d29kZXRhcHllaXF1Y25uaG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDk2NDEsImV4cCI6MjA1ODg4NTY0MX0.tdt8-o0YnotkP8BxZvV0GXMZIPqr3b9rZINCF_2sVvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);